from utils      import *


def generate_url_common_params(dev_info, extra={}):
    url_params = {
        'reg_store_region': dev_info['geo']['region'].lower(),
        'user_selected_region': 0,
        'residence': dev_info['geo']['region'],
        'device_id': dev_info['params']['device_id'],
        'os_version': dev_info['params']['os_version'],
        'iid': dev_info['params']['iid'],
        'app_name': 'musical_ly',
        'locale': dev_info['geo']['region'].lower(),
        'sys_region': dev_info['geo']['region'],
        'channel': 'App Store',
        'op_region': dev_info['geo']['region'],
        'os_api': dev_info['params']['os_api'],
        'idfa': dev_info['params']['idfa'],
        'device_platform': 'iphone',
        'openudid': dev_info['params']['openudid'],
        'tz_offset': dev_info['geo']['tz_offset'],
        'app_language': 'en',
        'build_number': dev_info['app']['build_number'],
        'aid': dev_info['app']['aid'],
        'uoo': '1',
        'content_language': 'en',
        'cdid': dev_info['params']['cdid'],
        'current_region': dev_info['geo']['region'],
        'app_version': dev_info['app']['app_version'],
        'ac': 'WIFI',
        'idfv': dev_info['params']['idfv'],
        'language': 'en',
        'version_code': dev_info['app']['app_version'],
        'account_region': dev_info['geo']['region'].lower(),
        'screen_width': dev_info['params']['screen_width'],
        'device_type': dev_info['extra']['iphone_model'],
        'tz_name': dev_info['geo']['tz_name'],
        'mcc_mnc': dev_info['geo']['mcc_mnc'],
        'vid': dev_info['extra']['vid'],
        "carrier_region1": dev_info['geo']['region'],
        "carrier_region": dev_info['geo']['carrier_region'],
        "support_webview": 1,
        "cronet_version": '4a87e515_2024-04-01',
        "ttnet_version": '4.2.137.41-tiktok',
        "use_store_region_cookie": 1,
        "ssmix": "a",
    }
    return urllib.parse.urlencode(url_params | extra)
